{"name": "test_three", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 == 2", "trace": "self = <test_mark_study.Test_Demo2 object at 0x0000025C4C3725E0>\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.smoke\n    @pytest.mark.demo\n    def test_three(self):\n        b= 2\n>       assert 0==b #注意这个用例会失败\nE       assert 0 == 2\n\ntest_mark_study.py:20: AssertionError"}, "start": 1618653266976, "stop": 1618653266977, "uuid": "eb536e14-5e16-4c61-ac0e-6f5ae3e3b183", "historyId": "d0603abf5d44504edca8f801f6750d23", "testCaseId": "24f8059f5ad4462629bbfcc3d3bbe9b9", "fullName": "test_mark_study.Test_Demo2#test_three", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "demo"}, {"name": "tag", "value": "smoke"}, {"name": "suite", "value": "test_mark_study"}, {"name": "subSuite", "value": "Test_Demo2"}, {"name": "host", "value": "LAPTOP-ATJKQH43"}, {"name": "thread", "value": "19672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_mark_study"}]}